// Package state owns the on-disk layout of state/ and the harness init
// command. It is responsible for creating every subdirectory that the
// design contract guarantees will be present after `harness init`, for
// seeding the default config.yaml, the role prompt files, the .gitignore,
// and a placeholder post-commit hook.
package state

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/victor-develop/advanced-tasker/internal/audit"
	"github.com/victor-develop/advanced-tasker/internal/gitops"
)

// Layout enumerates every relative directory `harness init` creates
// underneath the state root. The list is the source of truth for the
// inter-track contract: pollers (Tracks B and C) rely on these paths
// existing so they can write into inbox/new and sources/<src>.
var Layout = []string{
	"threads",
	"tasks",
	"inbox/new",
	"inbox/updates",
	"inbox/human",
	"inbox/agent-reports",
	"inbox/anomalies",
	"jobs/pending",
	"jobs/in-flight",
	"jobs/done",
	"jobs/failed",
	"outbox/pending",
	"outbox/awaiting-human",
	"outbox/sent",
	"outbox/failed",
	"tick-log",
	"sources/slack/cursors",
	"sources/github/cursors",
	"audit/reports",
	"telemetry/ticks",
	"telemetry/workers",
	"roles",
}

// DefaultConfigYAML mirrors design/02 §config.yaml + design/10 fields.
const DefaultConfigYAML = `mode: hybrid
git:
  auto_commit: true
models:
  driver: claude-p
  commander: claude-opus-4-7
  updater: claude-haiku-4-5
  worker_default: claude-sonnet-4-6
  auditor: claude-haiku-4-5
limits:
  dashboard_token_budget: 8000
  rollup_current_ask_max_lines: 3
  rollup_open_questions_max_lines: 5
  outbox_per_thread_per_hour: 5
  outbox_per_channel_per_hour: 20
  outbox_global_per_hour: 100
  outbox_high_risk_require_human: true
  outbox_revoke_window: 5m
pins:
  default_ttl: 7d
schedule:
  active_window:
    timezone: Asia/Singapore
    start: "08:00"
    end:   "20:00"
    interval: 3m
  inactive_window:
    interval: 30m
  event_triggered: true
  event_min_gap: 30s
audit:
  cadence: 4h
  problems_escalate_to_human: true
  watch_only_to_commander: true
rollup:
  debounce: 30s
sources:
  slack:
    enabled: true
  github:
    enabled: true
`

// gitignoreBody excludes the transient/short-lived areas per design/02:
// inbox/, jobs/, outbox/pending|awaiting-human|failed/, telemetry/. We do
// NOT ignore outbox/sent/ (it is git-tracked per design/07).
const gitignoreBody = `# state/.gitignore — what is NOT durable world model
# Generated by `+"`harness init`"+`.
#
# Short-lived queues and per-tick telemetry. See design/02 for rationale.
inbox/
jobs/
outbox/pending/
outbox/awaiting-human/
outbox/failed/
telemetry/

# Local secrets and per-machine overrides.
config.local.yaml
*.local.yaml
.env
.env.*
`

// postCommitHook re-runs the rollup ledger + human-pin guards against
// HEAD~1..HEAD as belt-and-suspenders per design/05 §Step 5. The shell
// hook invokes the harness binary which holds the validator logic
// (so the rules live in one place).
//
// On violation: the hook calls `git reset --hard HEAD~1` and drops an
// anomaly. We only run when HEAD touched a tracked rollup.md.
const postCommitHook = `#!/bin/sh
# state/.git/hooks/post-commit — installed by ` + "`harness init`" + `.
# Re-runs the rollup append-only ledger + human-pin guards against
# HEAD~1..HEAD per design/05 §"Post-commit hook re-validates".

set -e

# Find the harness binary. Honor $HARNESS_BIN if set, else PATH.
HARNESS_BIN="${HARNESS_BIN:-harness}"
if ! command -v "$HARNESS_BIN" >/dev/null 2>&1; then
  exit 0  # No harness binary available (e.g. during init); skip.
fi

# Skip if this is the very first commit (no HEAD~1).
if ! git rev-parse --verify -q HEAD~1 >/dev/null 2>&1; then
  exit 0
fi

CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -E '^threads/.*/rollup\.md$' || true)
if [ -z "$CHANGED" ]; then
  exit 0
fi

STATE_DIR=$(pwd)
for f in $CHANGED; do
  if ! "$HARNESS_BIN" --state-dir "$STATE_DIR" rollup verify-commit --file "$f" >/tmp/harness-hook.err 2>&1; then
    echo "post-commit hook: rollup violation in $f — reverting last commit" >&2
    cat /tmp/harness-hook.err >&2
    git reset --hard HEAD~1
    mkdir -p "$STATE_DIR/inbox/anomalies"
    cat >"$STATE_DIR/inbox/anomalies/post-commit-$(date -u +%Y%m%dT%H%M%S).json" <<EOF
{"source":"post-commit-hook","summary":"rollup ledger/pin violation in $f","detail_path":"/tmp/harness-hook.err"}
EOF
    exit 1
  fi
done
exit 0
`

// roleSeeds maps state/roles/<file> → its initial content. We seed
// trivial scaffolds so design/02 §Top-level layout is honored without
// pulling in any LLM-specific copy that may evolve.
var roleSeeds = map[string]string{
	"pr-reviewer.md":   "# pr-reviewer role\n\nEvaluate a PR diff and comments and recommend approve / request-changes / blocked.\n",
	"slack-drafter.md": "# slack-drafter role\n\nDraft a reply for a Slack thread. Workers never send directly; output is reviewed.\n",
	"planner.md":       "# planner role\n\nDecompose a goal into subtasks. Output is reviewed by the commander.\n",
	"researcher.md":    "# researcher role\n\nInvestigate a question and report findings with evidence.\n",
	"summarizer.md":    "# summarizer (rollup updater) role\n\nKeep one thread's rollup.md in sync with new raw events. See design/05.\n",
	"auditor.md":       "# auditor role\n\nRead-only meta-review of commander behavior. See design/11.\n",
}

// Init creates the state/ skeleton at root: every directory in Layout, a
// default config.yaml, a .gitignore, role prompt stubs, runs `git init`,
// and produces the initial commit.
//
// It is an error if root already contains a non-empty state directory.
func Init(root string) error {
	if root == "" {
		return fmt.Errorf("state root path must not be empty")
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("resolve state root: %w", err)
	}

	// Refuse to init over an existing harness state to avoid clobbering.
	if _, err := os.Stat(filepath.Join(abs, "config.yaml")); err == nil {
		return fmt.Errorf("state already initialized at %s (config.yaml exists)", abs)
	}

	if err := os.MkdirAll(abs, 0o755); err != nil {
		return fmt.Errorf("mkdir state root: %w", err)
	}

	for _, sub := range Layout {
		if err := os.MkdirAll(filepath.Join(abs, sub), 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", sub, err)
		}
	}

	// .gitignore inside state/.
	if err := os.WriteFile(filepath.Join(abs, ".gitignore"), []byte(gitignoreBody), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}

	// Default config.yaml.
	if err := os.WriteFile(filepath.Join(abs, "config.yaml"), []byte(DefaultConfigYAML), 0o644); err != nil {
		return fmt.Errorf("write config.yaml: %w", err)
	}

	// Seed role prompts.
	for name, body := range roleSeeds {
		fp := filepath.Join(abs, "roles", name)
		if err := os.WriteFile(fp, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write role %s: %w", name, err)
		}
	}

	// Seed audit/checklist.yaml.
	if err := os.WriteFile(filepath.Join(abs, "audit", "checklist.yaml"), []byte(audit.DefaultChecklist), 0o644); err != nil {
		return fmt.Errorf("write audit checklist: %w", err)
	}

	// Drop a .gitkeep in every otherwise-empty git-tracked directory so
	// the initial commit captures the structure (git does not track empty
	// dirs). We omit .gitkeep from gitignored subtrees (inbox, jobs, etc.)
	// because those are explicitly excluded.
	for _, sub := range []string{"threads", "tasks", "tick-log", "audit/reports", "outbox/sent", "sources/slack/cursors", "sources/github/cursors"} {
		fp := filepath.Join(abs, sub, ".gitkeep")
		if err := os.WriteFile(fp, []byte(""), 0o644); err != nil {
			return fmt.Errorf("write .gitkeep %s: %w", sub, err)
		}
	}

	// git init + initial commit.
	r := gitops.Repo{Dir: abs}
	if err := r.Init(); err != nil {
		return fmt.Errorf("git init: %w", err)
	}

	// Install post-commit hook AFTER `git init` so .git/hooks exists.
	hookPath := filepath.Join(abs, ".git", "hooks", "post-commit")
	if err := os.WriteFile(hookPath, []byte(postCommitHook), 0o755); err != nil {
		return fmt.Errorf("install post-commit hook: %w", err)
	}

	if err := r.AddAll(); err != nil {
		return fmt.Errorf("git add: %w", err)
	}
	if _, err := r.Commit("init harness: create state skeleton"); err != nil {
		return fmt.Errorf("initial commit: %w", err)
	}

	return nil
}

// Resolve returns the absolute path of the state root to use, honoring
// (in order): explicit override, the HARNESS_STATE env var, and the
// default ./state.
func Resolve(override string) (string, error) {
	if override != "" {
		return filepath.Abs(override)
	}
	if env := os.Getenv("HARNESS_STATE"); env != "" {
		return filepath.Abs(env)
	}
	return filepath.Abs("state")
}

// IsInitialized reports whether root looks like a harness state dir.
func IsInitialized(root string) bool {
	_, err := os.Stat(filepath.Join(root, "config.yaml"))
	if err != nil {
		return false
	}
	_, err = os.Stat(filepath.Join(root, ".git"))
	return err == nil
}
